//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_contractor()
        {
            this.t_vouchers_contractor = new HashSet<t_vouchers_contractor>();
        }
    
        public int C_id { get; set; }
        public string C_name { get; set; }
        public string C_sex { get; set; }
        public string C_adresse { get; set; }
        public string C_phone { get; set; }
        public Nullable<int> C_idContractor { get; set; }
        public string C_status_system { get; set; }
    
        public virtual t_contractor t_contractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_vouchers_contractor> t_vouchers_contractor { get; set; }
    }
}
