//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BANROEntities : DbContext
    {
        public BANROEntities()
            : base("name=BANROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_centre_soins> t_centre_soins { get; set; }
        public virtual DbSet<employee_contractor> employee_contractor { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<t_beneficiaires> t_beneficiaires { get; set; }
        public virtual DbSet<t_bon_commandes> t_bon_commandes { get; set; }
        public virtual DbSet<t_categories> t_categories { get; set; }
        public virtual DbSet<t_contractor> t_contractor { get; set; }
        public virtual DbSet<t_departement> t_departement { get; set; }
        public virtual DbSet<t_factures> t_factures { get; set; }
        public virtual DbSet<t_logger> t_logger { get; set; }
        public virtual DbSet<T_logs> T_logs { get; set; }
        public virtual DbSet<t_sickness> t_sickness { get; set; }
        public virtual DbSet<t_succursales> t_succursales { get; set; }
        public virtual DbSet<t_test> t_test { get; set; }
        public virtual DbSet<t_vouchers_casuals> t_vouchers_casuals { get; set; }
        public virtual DbSet<t_vouchers_contractor> t_vouchers_contractor { get; set; }
    }
}
