//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_beneficiaires
    {
        public int C_id { get; set; }
        public string C_id_succ { get; set; }
        public string C_mat { get; set; }
        public string C_name { get; set; }
        public string C_datenais { get; set; }
        public string C_sex { get; set; }
        public string C_statusmaritalk { get; set; }
        public string C_phone { get; set; }
        public string C_picture { get; set; }
        public string C_id_partenaire { get; set; }
        public string C_id_parent { get; set; }
        public string C_id_categorie { get; set; }
        public Nullable<int> C_id_depart { get; set; }
        public string C_statusChild { get; set; }
        public string C_id_visitor { get; set; }
        public string C_motif_visit { get; set; }
        public string C_status_system { get; set; }
        public string C_company_visitor { get; set; }
        public string C_company_visited { get; set; }
    }
}
