//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_bon_commandes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_bon_commandes()
        {
            this.t_factures = new HashSet<t_factures>();
        }
    
        public int C_id_bon { get; set; }
        public Nullable<int> C_id_bene { get; set; }
        public Nullable<int> C_id_centre { get; set; }
        public string C_datedeb { get; set; }
        public string C_datefin { get; set; }
        public string C_namedoctor { get; set; }
        public string C_approuve { get; set; }
        public string C_motif { get; set; }
    
        public virtual t_centre_soins t_centre_soins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_factures> t_factures { get; set; }
    }
}
