//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_centre_soins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_centre_soins()
        {
            this.t_bon_commandes = new HashSet<t_bon_commandes>();
            this.t_vouchers_casuals = new HashSet<t_vouchers_casuals>();
            this.t_vouchers_contractor = new HashSet<t_vouchers_contractor>();
        }
    
        public int C_id_centre { get; set; }
        public string C_name { get; set; }
        public string adresse { get; set; }
        public string C_phone { get; set; }
        public string C_status_system { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_bon_commandes> t_bon_commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_vouchers_casuals> t_vouchers_casuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_vouchers_contractor> t_vouchers_contractor { get; set; }
    }
}
