//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_contractor()
        {
            this.employee_contractor = new HashSet<employee_contractor>();
        }
    
        public int C_id { get; set; }
        public string C_name { get; set; }
        public string C_adresse { get; set; }
        public string C_phone { get; set; }
        public string C_idSucc { get; set; }
        public string C_status_system { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_contractor> employee_contractor { get; set; }
        public virtual t_succursales t_succursales { get; set; }
    }
}
