//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_departement
    {
        public int C_id { get; set; }
        public string C_id_depart { get; set; }
        public string C_id_succ { get; set; }
        public string C_status_system { get; set; }
    
        public virtual t_succursales t_succursales { get; set; }
    }
}
