//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_factures
    {
        public int C_id_fact { get; set; }
        public Nullable<int> C_id_bon { get; set; }
        public string C_datefacture { get; set; }
        public string C_timefacture { get; set; }
        public Nullable<decimal> C_cout { get; set; }
        public string C_fileupload { get; set; }
    
        public virtual t_bon_commandes t_bon_commandes { get; set; }
    }
}
