//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_logger
    {
        public int C_id { get; set; }
        public string C_username { get; set; }
        public string password { get; set; }
        public string C_priority { get; set; }
        public string C_idSucc { get; set; }
        public Nullable<int> C_employeeId { get; set; }
        public string C_status_system { get; set; }
    }
}
