//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_logs
    {
        public int C_id { get; set; }
        public string C_user { get; set; }
        public string C_date { get; set; }
        public string C_time { get; set; }
        public string C_action { get; set; }
        public string C_object { get; set; }
        public string C_company { get; set; }
        public string C_mat { get; set; }
    }
}
