//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_vouchers_casuals
    {
        public int C_id_voucher { get; set; }
        public string C_name_casual { get; set; }
        public string C_company_casual { get; set; }
        public string C_date_casual { get; set; }
        public string C_motif { get; set; }
        public Nullable<int> C_id_centre { get; set; }
        public string C_id_company { get; set; }
        public string C_department { get; set; }
        public string C_cause { get; set; }
        public Nullable<decimal> C_cout { get; set; }
        public string C_service { get; set; }
        public string C_datenaiss { get; set; }
    
        public virtual t_centre_soins t_centre_soins { get; set; }
        public virtual t_succursales t_succursales { get; set; }
    }
}
